forms/urls.py
from django.urls import path
from . import views

app_name = 'forms'

urlpatterns = [
    path('', views.index, name='forms'),
    path('submit/', views.submit, name="submit"),
	path('delete/<int:friendsModel_id>/', views.deleteItem, name="delete")
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
	path('extra/', views.extra, name='extra'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('friends/', include('forms.urls'))
]

forms/models.py
from django.db import models

# Create your models here.

#class YearClass(models.Model):
#	BATCH = [
#	('2016','2016'),
#	('2017','2017'),
#	('2018','2018'),
#	('2019','2019'),zzz
#	]
#	classYear = models.CharField(choices=BATCH,max_length=4, default='2018')
#	def __str__(self):
#		return self.classYear
		

class friendsModel(models.Model):
	name = models.CharField(max_length = 30)
	hobby = models.CharField(max_length = 50)
	favFood = models.CharField(max_length = 20)
	ClassYear = models.CharField(max_length = 5, default= 2018)
#	ClassYear = models.ForeignKey(YearClass, on_delete=models.CASCADE, default='Fasilkom')
	def __str__(self):
		return self.name

homepage/models.py
from django.db import models

# Create your models here.

forms/admin.py
from django.contrib import admin

# Register your models here.

forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

forms/tests.py
from django.test import TestCase

# Create your tests here.

forms/views.py
from django.shortcuts import render, redirect
from .models import friendsModel
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
	friends = friendsModel.objects.all()
	content = {
		"friendList" : friends
	}
	return render(request, 'forms.html', content)

@csrf_exempt
def submit(request):
	friends_name = request.POST.get('nama')
	friends_hobby = request.POST.get('hobby')
	friends_favfood = request.POST.get('favfood')
	friends_classYear = request.POST.get('classYear')
	new_friend = friendsModel(name=friends_name, hobby=friends_hobby, favFood=friends_favfood, ClassYear=friends_classYear)
	new_friend.save()
	return redirect('forms:forms')
	
	
def deleteItem(request, friendsModel_id):
    item = friendsModel.objects.get(id=friendsModel_id)
    item.delete()
    return redirect('forms:forms')

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def extra(request):
    return render(request, 'extra.html')
	

forms/templates/forms.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Friend List</title>

    <!-- Bootstrap CSS -->
	<link rel="stylesheet"      ="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/index.css' %}">
<style>
body{
background-color: gray;
}
</style>

</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark  fixed-top id="mainNav">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav ml-auto">
			{% include 'navbar.html' %}
		</button>
			</ul>
		</div>
	</nav>



    <form class="m-5" method="POST" action="{% url 'forms:submit' %}">
        {% csrf_token %}
		
        <div class="container">

            <div class="form-group">
              <label for="nama">Name :</label>
              <input type="text" class="form-control" id="nama" name="nama">
            </div>

            <div class="form-group">
                <label for="hobby">Hobby :</label>
                <input type="text" class="form-control" id="hobby" name="hobby">
            </div>

            <div class="form-group">
                <label for="favfood">Favorite Food :</label>
                <input type="text" class="form-control" id="favfood" name='favfood'>
            </div>

            <div class="form-group">
				<label for="classYear">Batch :</label>
                <select class="form-control form-control-sm mb-3" type="text" id='classYear' name='classYear'>
					<option>2016</option>
                    <option>2017</option>
                    <option>2018</option>
					<option>2019</option>
                  </select>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>

      <div class="container">
          {% for friends in friendList %}
			<form action="{% url 'forms:delete' friends.id %}" method="POST">
            {% csrf_token %}
                    <h4><strong><br>{{ friends.name }}</h4>
                    <p>Hobby         : {{ friends.hobby }}</p>
                    <p>Favorite Food : {{ friends.favFood }}</p>
					<p>Batch         : {{ friends.ClassYear }}</p>
                    <button type="submit" class="btn btn-primary" value="delete">Delete
                    </button>
			</form>
          {% endfor %}
      </div>


    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

homepage/templates/copyright.html
<div style="color: #777;background-color:white;text-align:center;text-align:justify;margin-top:10px">
<h4 style="text-align:center;">Copyright 2020 (c)</h4>
<p style="text-align:center">Priagung mager nyari logo</p>
</div>

homepage/templates/extra.html
<!DOCTYPE html>
<html lang = "en-US">
 <head>
	{% load static %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/index.css' %}">
<title>Extrapage</title>
 </head>
 <body>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark  fixed-top id="mainNav">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      {% include 'navbar.html' %}
   </button>
    </ul>
  </div>
</nav>
	
<div class="parallax" id="parallax4">
<h3 style="text-align:center; padding-top:70vh; padding-right:5%;font-size:5vh">S C R E E N S H O T S</h3>
</div>

<div class="row"> 
  <div class="column">
    <img src="{% static 'images/faceit.png'%}" style="width:100%">
    <img src="{% static 'images/tetogre.png'%}" style="width:100%">
    <img src="{% static 'images/csgohours.png'%}" style="width:100%">
    <img src="{% static 'images/steamuser.png'%}" style="width:100%">
	<img src="{% static 'images/faceit.png'%}" style="width:100%">
    <img src="{% static 'images/tetogre.png'%}" style="width:100%">
    <img src="{% static 'images/csgohours.png'%}" style="width:100%">
  </div>
  <div class="column">
    <img src="{% static 'images/faceit.png'%}" style="width:100%">
    <img src="{% static 'images/tetogre.png'%}" style="width:100%">
    <img src="{% static 'images/csgohours.png'%}" style="width:100%">
	<img src="{% static 'images/faceit.png'%}" style="width:100%">
    <img src="{% static 'images/tetogre.png'%}" style="width:100%">
    <img src="{% static 'images/csgohours.png'%}" style="width:100%">
    <img src="{% static 'images/steamuser.png'%}" style="width:100%">
  </div>  
  <div class="column">
	<img src="{% static 'images/faceit.png'%}" style="width:100%">
    <img src="{% static 'images/tetogre.png'%}" style="width:100%">
	<img src="{% static 'images/faceit.png'%}" style="width:100%">
    <img src="{% static 'images/tetogre.png'%}" style="width:100%">
    <img src="{% static 'images/csgohours.png'%}" style="width:100%">
    <img src="{% static 'images/csgohours.png'%}" style="width:100%">
    <img src="{% static 'images/steamuser.png'%}" style="width:100%">
  </div>
  <div class="column">
    <img src="{% static 'images/faceit.png'%}" style="width:100%">
    <img src="{% static 'images/tetogre.png'%}" style="width:100%">
    <img src="{% static 'images/csgohours.png'%}" style="width:100%">
	<img src="{% static 'images/faceit.png'%}" style="width:100%">
    <img src="{% static 'images/tetogre.png'%}" style="width:100%">
    <img src="{% static 'images/csgohours.png'%}" style="width:100%">
    <img src="{% static 'images/steamuser.png'%}" style="width:100%">
  </div>
</div>

{% include 'copyright.html' %}

</body>
</html>
	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	
 </body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	 <link rel = "stylesheet" type = "text/css" href = "{% static 'css/index.css' %}">
<style>
</style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark  fixed-top id="mainNav">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#bio">Bio</a>
      </li>
	  <li class="nav-item">
        <a class="nav-link" href="#projects">Projects</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#parallax3">Contacts</a>
      </li>
	  <li class="nav-item">
		<a href="#" class="btn btn-secondary" data-toggle="modal" data-target="#videoModal" data-theVideo="https://www.youtube.com/embed/dQw4w9WgXcQ?start=2">VIDEO</a>
	  </li>
	  
	  </ul>
	  <ul class="navbar-nav ml-auto">
      {% include 'navbar.html' %}
	 
</button>
    </ul>
  </div>
</nav>


<div class="parallax" id="parallax1">
<h3 style="text-align:right; padding-top:10vh; padding-right:5%;font-size:5vh"> W E L C O M E<br>T O<br>M Y<br> W E B S I T E</h3>
</div>

<div class="split" id="bio">
<div class="left">
<object align="right" style="vertical-align:middle">
<img src="{% static 'images/Photo1.png' %}" alt="Photo" class="centeredimg">
</object>
</center>
</div>
<div class="right">
    <h2 class="titlenameright">Priagung Satria Wicaksana</h2>
    <p class="descright">Undergraduate Student<br>Currently on 4th Semester<br>Faculty of Computer Science<br> University of Indonesia</p>
</div>
</div>

<div class="split2">
<div class="left2" style="border-top:1px solid white">
<h2 class="titlenameleft">My hobbies:</h2>
	<p class="descleft">I like playing games and sleep<br>Casually playing every game i find<br>Currently addicted to Black Desert Online</p>
</div>
<div class="right2" style="border-top:1px solid white"> 
	<h2 class="titlenameright">About me:</h2>
	<p class="descright">I code in Java and Python<br>Currently learning Javascript, HTML, and CSS</p>
</div>
</div>

<div class="parallax" id="parallax2"> </div>

<div style="color: #777;background-color:white;text-align:center;padding:50px 80px;text-align:justify;" id="projects">
	<h3 class="gittitle">GitLab Projects</h3>
	<p class="gitname"> 
	<br>
	<a href="https://gitlab.com/priagung/advprog-tutorial">Advanced Programming 2020</a>
	<br><br><br>
	<a href="https://gitlab.com/priagung/ppw">PPW Task0</a>
	<br><br><br>
	<a href="https://gitlab.com/priagung/the-art-of-git">The Art of Git</a>
	<br><br><br>
	<a href="https://gitlab.com/priagung/ppw-story-3">This Project</a>
	</p>
</div>

<div class="parallax" id="parallax3"></div>

<div style="color: #777;background-color:white;text-align:center;padding:50px 80px;text-align:justify;">
	<h3 style="text-align:center;">My Contacts :</h3>
	
	<p style="text-align:center"> 
		<a href="https://gitlab.com/priagung">
		<img border="0" alt="Gitlab" src="{% static 'images/gitlab.png' %}" width="100" height="100"></a>
		<a href="https://www.instagram.com/therealairp/">
		<img border="0" alt="Instagram" src="{% static 'images/ig.png' %}" width="100" height="100"></a>
		<a href="https://steamcommunity.com/id/airP">
		<img border="0" alt="Steam" src="{% static 'images/steam.png' %}" width="100" height="100"></a>
		<a href="https://discord.gg/ngfDGFy">
		<img border="0" alt="Discord" src="{% static 'images/discord.png' %}" width="100" height="100"></a>
		<a href="https://www.youtube.com/channel/UCopKVLCpSEvYf_3Sz5Yv66w">
		<img border="0" alt="Youtube" src="{% static 'images/youtube.png' %}" width="100" height="100"></a>
	</p>

</div>

<div class="parallax" id="parallax4"></div>
{% include 'copyright.html' %}

<div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div>
          <iframe width="100%" height="350" src=""></iframe>
        </div>
      </div>
    </div>
  </div>
</div>


 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script> //FUNCTION TO GET AND AUTO PLAY YOUTUBE VIDEO FROM DATATAG
	function autoPlayYouTubeModal(){
	var trigger = $("body").find('[data-toggle="modal"]');
	trigger.click(function() {
		var theModal = $(this).data( "target" ),
		videoSRC = $(this).attr( "data-theVideo" ), 
		videoSRCauto = videoSRC+"?autoplay=1" ;
		$(theModal+' iframe').attr('src', videoSRCauto);
		$(theModal+' button.close').click(function () {
			$(theModal+' iframe').attr('src', videoSRC);
			});   
		});
	}
	$(document).ready(function(){
		autoPlayYouTubeModal();
		});
	</script>

</body>
</html>

homepage/templates/navbar.html
<li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
      </li>
	  <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:extra' %}">Games</a>
  </li>
<li class="nav-item">
	<a class="nav-link" href="/friends">Friendlist</a>